name: Run tests and deploy project
on: [push, workflow_dispatch]
jobs:
  lint:
    runs-ons: ubuntu-latest
    steps:
    - name: Start process
      run: echo "Starting liner"
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install NodeJS
      uses: actions/setup-node@v3
    - name: Install dependencies
      run: npm ci
    - name: Run linter
      run: npm lint
    - name: End linter
      run: echo "Finish linting"
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: Start  process
      run: echo "Starting process"
    - name: Checkout code from repository
      uses: actions/checkout@v3
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps: 
    - name: state step
      run: echo "Starting deployment step"
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Build project
      run: npm run build
    - name: Deploy
      run: echo "Deploying ..."
        

