name: Scheduled Workflow

on:
  schedule:
    - cron: '*/15 * * * *' # Runs every 15 minutes

jobs:
  echo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo "hello action"
        run: echo "hello action"
