name: Run tests and deploy project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Start  process
      run: echo "Starting process"
    - name: Checkout code from repository
      uses: actions/checkout@v3
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test
  deploy:
    runs-on: ubuntu-latest
    steps: 
    - name: state step
      run: echo "Starting deployment step"
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install NodeKS
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Build project
      run: npm run build
    - name: Deploy
      run: echo "Deploying ..."
        

